module.exports = {
  names: [
    "Amiah Gaines",
    "Jordyn Randolph",
    "Mollie Maldonado",
    "Kiley Santana",
    "Isla Nash",
    "Orlando Morrow",
    "Aditya Huerta",
    "Deborah Pacheco",
    "Abigail Deleon",
    "Jacey Thompson",
    "Avah Benson",
    "Camryn Jefferson",
    "Ean Pace",
    "Judah Malone",
    "Julianna Molina",
    "Raphael Novak",
    "Griffin Rangel",
    "Leila Avila",
    "Alexia Yu",
    "Drew Romero"
  ],
  countries: [
    "United Kingdom",
    "United States",
    "Albania",
    "Afghanistan",
    "Algeria",
    "Andorra",
    "Anguilla",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Angola",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia-Herzegovina",
    "Botswana",
    "Brazil",
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Cambodia",
    "Canada",
    "Cape Verde Islands",
    "Cayman Islands",
    "Chile",
    "Côte d'Ivoire",
    "China",
    "Colombia",
    "Comoros Islands",
    "Cook Islands",
    "Costa Rica - San José",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Estonia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guyana",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Isle of Man",
    "Indonesia",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kyrgyzstan",
    "Kuwait",
    "Laos",
    "Latvia",
    "Liberia",
    "Lebanon",
    "Lesotho",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Malta",
    "Martinique",
    "Mauritius",
    "Mexico",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Norway",
    "Oman",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russia",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome + Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "South Africa",
    "South Korea",
    "Spain",
    "Spain - Canary Islands",
    "Sri Lanka",
    "St Barthelemy",
    "Syria",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Taiwan ROC",
    "Tanzania",
    ":Turkmenistan",
    "Thailand",
    "Timor Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Tajikistan",
    "U.S. Virgin Islands",
    "Ukraine",
    "Uzbekistan",
    "United Arab Emirates",
    "Uruguay",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Zimbabwe"
  ]
};
